#494 Favicon Added
Eduhub-Community/Eduhub-Community.github.io pull request #495
Opened 2023-07-10 16:26 UTC by PVBharadwaj

## Related Issue

Closes #494 

## Description

The main index.html file is spotted out. An attempt to change the favicon is already done. But it was not reflected in the website as there is a div class before it. I removed it and the favicon is being displayed now.

## Screenshots
Before the change
<img width="153" alt="image" src="https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/117581755/42a6166b-d42d-4357-a7de-709cc6bda49c">

After the change
<img width="162" alt="image" src="https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/117581755/973e1be8-0301-479e-ba40-ba2309277e16">

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

2023-07-11 05:12 UTC, AshAman999 requested changes

2023-07-11 05:12 UTC, AshAman999 commented on index.html
> -<div id="seo"></div>
this is important as well, can you trying moving seo after favicon

2023-07-11 05:32 UTC, PVBharadwaj commented on index.html
> -<div id="seo"></div>
sure

2023-07-11 05:32 UTC, Viveksati5143 approved these changes

2023-07-11 05:33 UTC, PVBharadwaj commented
@AshAman999 I have made the required changes. Please review them.

2023-07-11 12:59 UTC, AshAman999 approved these changes

2023-07-11 12:59 UTC, merged

2023-07-12 03:41 UTC, PVBharadwaj commented
@AshAman999  I am a GSSoC'23 contributor. The score for this PR is not added to the leaderboard. Please consider this PR under GSSoC'23

2023-08-08 02:04 UTC, PVBharadwaj commented
> @AshAman999 I am a GSSoC'23 contributor. The score for this PR is not added to the leaderboard. Please consider this PR under GSSoC'23

@AshAman999  The score was still not added to the leaderboard. Please add GSSOC'23 label to the PR. It has been a month since the PR got merged.

2023-08-08 04:22 UTC, AshAman999 commented
Check now @PVBharadwaj

2023-08-08 13:34 UTC, PVBharadwaj commented
@AshAman999  The score was not added. Please check.