feat: Added 7 workflow Files in GitHub Workflows Folder
Eduhub-Community/Eduhub-Community.github.io pull request #545
Opened 2023-08-10 05:04 UTC by NarendraKoya999

## Related Issue

Closes #526 

## Description
- **Added 7 workflow Files in .github/workflows Folder for Future Use.**
- **Whatever Mentioned in My Issue Description except deno.yml File, remained All workflow Files are Added.**
- **Instead of deno.yml File, Additionally added pr_close_greet.yml and issue_close_greet.yml Files. These files are Very Helpful and Nobody Raised these Two.**

## Screenshots

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

2023-08-10 05:05 UTC, NarendraKoya999 commented
Hi @AshAman999 . Please Review on this PR as soon as Possible and Valid Level Label under GSSOC'23. Thank You !

2023-08-10 18:12 UTC, AshAman999 commented
It will take some time for me to review it @NarendraKoya999 
I am not an expert in github actions  🫤

2023-08-11 14:21 UTC, NarendraKoya999 commented
Hi @AshAman999 . Any Update on this PR?

2023-09-04 11:15 UTC, Viveksati5143 commented on .github/workflows/pr_close_greet.yml
> +                const commentBody = `Thank you  @${commentAuthor} , for your valuable time and contribution in our Pentesting-and-Hacking-Scripts. \n \n  Hoping to see you soon with another PR again
```suggestion
                const commentBody = `Thank you  @${commentAuthor} , for your valuable time and contribution in our `Eduhub-Community`. \n \n  Hoping to see you soon with another PR again 😇 \n Wishing you all the best for your journey into Open Source🚀
```

2023-09-04 11:18 UTC, Viveksati5143 requested changes
x

2024-08-24 04:36 UTC, closed without merging